grape-suite:0.1.0
typst/packages pull request #600
Opened 2024-04-28 14:17 UTC by piepert

I am submitting
- [x] a new package
- [ ] an update for a package

Description: Explain what the package does and why it's useful.

I have read and followed the submission guidelines and, in particular, I
- [x] selected a name that isn't the most obvious or canonical name for what the package does
- [x] added a `typst.toml` file with all required keys
- [x] added a `README.md` with documentation for my package
- [x] have chosen a license and added a `LICENSE` file or linked one in my `README.md`
- [x] tested my package locally on my system and it worked
- [x] `exclude`d PDFs or README images, if any, but not the LICENSE

- [x] ensured that my package is licensed such that users can use and distribute the contents of its template directory without restriction, after modifying them through normal use.

2024-04-28 15:44 UTC, tingerrr requested changes

2024-04-28 15:44 UTC, tingerrr commented on packages/preview/grape-suite/0.1.0/typst.toml
> +thumbnail = "thumbnail.typ"
```suggestion
thumbnail = "thumbnail.png"
```

2024-04-28 15:50 UTC, piepert commented on packages/preview/grape-suite/0.1.0/typst.toml
> +thumbnail = "thumbnail.typ"
Thanks!

2024-05-03 08:19 UTC, elegaanz commented
Thanks!

2024-05-03 08:19 UTC, merged